-------------------------------------------------------------------------------
Test set: in.inbalokesh.onlyhomefood.TestCreateUser
-------------------------------------------------------------------------------
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.524 s <<< FAILURE! - in in.inbalokesh.onlyhomefood.TestCreateUser
in.inbalokesh.onlyhomefood.TestCreateUser.testCreateUserWithValidInput()  Time elapsed: 2.52 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception thrown: java.lang.RuntimeException
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:83)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:54)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:37)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3135)
	at in.inbalokesh.onlyhomefood.TestCreateUser.testCreateUserWithValidInput(TestCreateUser.java:23)
Caused by: java.lang.RuntimeException
	at in.inbalokesh.onlyhomefood.dao.UserDAO.create(UserDAO.java:76)
	at in.inbalokesh.onlyhomefood.service.UserService.create(UserService.java:28)
	at in.inbalokesh.onlyhomefood.TestCreateUser.lambda$testCreateUserWithValidInput$0(TestCreateUser.java:24)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:50)
	... 16 more

